# Generated by Django 5.0.6 on 2024-07-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_placeimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Айди'),
        ),
    ]
